Use print colors in die function

diff --git a/scripts/ccrun b/scripts/ccrun
--- a/scripts/ccrun
+++ b/scripts/ccrun
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 die(){
-    >&2 echo "ccrun: ERROR: $*"
+    >&2 echo -e "ccrun: \033[1;31merror:\033[0m \033[1;37m$*\033[0m"
     exit 1
 }
 
@@ -102,6 +102,7 @@ while [[ $# > 0 ]]; do
                         cflags="$1"
                         ;;
                     D)
+                        debug=1
                         debugger="$1"
                         ;;
                 esac
@@ -122,9 +123,8 @@ else # no .cpp in files
 fi
 [[ $debug == 1 ]] && cflags="-g $cflags"
 "$cc" $cflags "${files[@]}" -o "$output" 
-code=$?
-[[ $code == 0 ]] || exit $code
-if [[ $no_run == 0 && $debug == 0 ]]; then
+[[ $? == 0 ]] || die "could not compile" # if the compiler failed exit
+if [[ $no_run == 0 && $debug == 0 ]]; then # running not in debug
     "$output" "$@"
 elif [[ $debug == 1 ]]; then
     "$debugger" "$output" "$@"
