Make todos script POSIX compliant

diff --git a/scripts/todos b/scripts/todos
--- a/scripts/todos
+++ b/scripts/todos
@@ -1,7 +1,7 @@
-#!/bin/bash
+#!/bin/sh
 
 die(){
-    >&2 echo -e "todos: \033[1;31merror:\033[0m \033[1;37m$*\033[0m" # print colored output to sterr
+    >&2 echo "todos: \033[1;31merror:\033[0m \033[1;37m$*\033[0m" # print colored output to sterr
     exit 1 # exit with error
 }
 
@@ -21,32 +21,23 @@ EOF
 using_depth=false
 target_path=.
 
-while [[ $# -gt 0 ]]; do
+while [ $# -gt 0 ]; do
     case $1 in
-        -h|--help)
-            print_help
-            exit
-            ;;
+        -h|--help) print_help; exit;;
         -p|--path)
             shift
-            [[ $# -gt 0 ]] || die "Expected an argument for -p"
+            [ $# -gt 0 ] || die "Expected an argument for -p"
             target_path="$1"
             ;;
         -d|--depth)
             shift
-            [[ $# -gt 0 ]] || die "Expected an argument for -d"
+            [ $# -gt 0 ] || die "Expected an argument for -d"
             maxdepth="$1"
             using_depth=true
             ;;
-        --*)
-            die "Unexpected long flag '$1'"
-            ;;
-        -*)
-            die "Unexpected flag '$1'"
-            ;;
-        *)
-            die "Unexpected arg $1"
-            ;;
+        --*) die "Unexpected long flag '$1'";;
+        -*) die "Unexpected flag '$1'";;
+        *) die "Unexpected arg $1";;
     esac
     shift
 done
